/**
 * Storybook Stories for Two-Factor Authentication Setup Page
 * 
 * This file contains various story configurations to showcase different
 * states and use cases of the 2FA setup component.
 * 
 * Stories include:
 * - Default configuration
 * - Different theme variants (dark, gradient)
 * - Custom account details
 * - Custom backup codes
 * - Error scenarios
 * - Interactive demos
 * 
 * @file
 */

import { TwoFactorAuthSetupPage } from "./index";
import type { Meta, StoryObj } from "@storybook/react-vite";

/**
 * Storybook metadata configuration
 * 
 * This defines the component's display name, description, and controls
 * available in the Storybook UI.
 */
const meta: Meta<typeof TwoFactorAuthSetupPage> = {
  title: "Templates/Pages/Authentication/Two Factor Authentication",
  component: TwoFactorAuthSetupPage,
  parameters: {
    layout: "fullscreen", // Full screen layout for better page preview
    docs: {
      description: {
        component:
          "A comprehensive Two-Factor Authentication (2FA) setup page with QR code display, manual code entry, backup codes management, and verification step. Includes all features needed for secure 2FA setup flow.",
      },
    },
  },
  argTypes: {
    secretKey: {
      control: { type: "text" },
      description: "Secret key for authenticator app (usually provided by backend)",
    },
    accountName: {
      control: { type: "text" },
      description: "Account identifier (email or username)",
    },
    issuer: {
      control: { type: "text" },
      description: "Issuer name (your app/service name)",
    },
    backupCodes: {
      control: { type: "object" },
      description: "Backup codes generated by backend",
    },
    variant: {
      control: { type: "select" },
      options: ["default", "dark", "gradient"],
      description: "Visual theme variant",
    },
    onVerify: {
      action: "verified", // Logs to Storybook Actions panel
      description: "Callback when verification code is submitted",
    },
    onSaveBackupCodes: {
      action: "backup-codes-saved", // Logs to Storybook Actions panel
      description: "Callback when backup codes are saved",
    },
  },
  tags: ["autodocs"], // Enables automatic documentation generation
};

export default meta;
type Story = StoryObj<typeof TwoFactorAuthSetupPage>;

// ============================================================================
// DEFAULT STORY
// ============================================================================

/**
 * Default story with standard configuration
 * 
 * This is the baseline story that shows the component with typical
 * default values. Use this as a reference for other stories.
 */
export const Default: Story = {
  args: {
    secretKey: "JBSWY3DPEHPK3PXP", // Demo secret key (base32 encoded)
    accountName: "user@example.com",
    issuer: "Your App",
    variant: "default",
    onVerify: async (code: string) => {
      // Simulate API call delay
      await new Promise((resolve) => setTimeout(resolve, 1000));
      // In a real application, this would validate the code with your backend
      // Example: const response = await fetch('/api/verify-2fa', { method: 'POST', body: JSON.stringify({ code }) });
      return { success: true, message: "2FA setup verified successfully", code: code };
    },
    onSaveBackupCodes: (codes: string[]) => {
       
      console.log("Backup codes saved:", codes);
      // In a real application, you might want to track this event
      // Example: analytics.track('2fa_backup_codes_saved');
    },
  },
};

// ============================================================================
// THEME VARIANTS
// ============================================================================

/**
 * Dark theme variant
 * 
 * Shows the component with dark background and dark-themed card.
 * Useful for applications with dark mode support.
 */
export const DarkTheme: Story = {
  args: {
    ...Default.args,
    variant: "dark",
  },
  parameters: {
    backgrounds: {
      default: "dark", // Set Storybook background to dark for better preview
    },
  },
};

/**
 * Gradient theme variant
 * 
 * Shows the component with a vibrant gradient background.
 * Useful for modern, eye-catching designs.
 */
export const GradientTheme: Story = {
  args: {
    ...Default.args,
    variant: "gradient",
  },
};

// ============================================================================
// CUSTOM CONFIGURATIONS
// ============================================================================

/**
 * Story with custom account details
 * 
 * Demonstrates how the component looks with different account information.
 * The QR code and manual entry will reflect these values.
 */
export const CustomAccount: Story = {
  args: {
    ...Default.args,
    accountName: "john.doe@company.com",
    issuer: "Company Portal",
    secretKey: "MFRGG43FMZQXIZLT", // Different secret key for demo
  },
};

/**
 * Story with custom backup codes
 * 
 * Shows how the component handles custom backup codes provided by the backend.
 * In production, these would be generated server-side.
 */
export const CustomBackupCodes: Story = {
  args: {
    ...Default.args,
    backupCodes: [
      "ABCD-1234",
      "EFGH-5678",
      "IJKL-9012",
      "MNOP-3456",
      "QRST-7890",
      "UVWX-1357",
      "YZAB-2468",
      "CDEF-3691",
    ],
  },
};

// ============================================================================
// ERROR SCENARIOS
// ============================================================================

/**
 * Verification failure scenario
 * 
 * Demonstrates how the component handles verification failures.
 * Useful for testing error states and user feedback.
 */
export const VerificationFailure: Story = {
  args: {
    ...Default.args,
    onVerify: async (code: string) => {
      // Simulate API call delay
      await new Promise((resolve) => setTimeout(resolve, 1000));
      // Always return failure for this story
      return {
        success: false,
        message: "Invalid code. Please check your authenticator app and try again.",
        code: code
      };
    },
  },
};

// ============================================================================
// EDGE CASES
// ============================================================================

/**
 * Story with long issuer and account names
 * 
 * Tests how the component handles longer text values.
 * Useful for ensuring responsive design and text overflow handling.
 */
export const LongIssuerName: Story = {
  args: {
    ...Default.args,
    issuer: "Very Long Company Name Application Portal",
    accountName: "very.long.email.address@verylongdomainname.com",
  },
};

// ============================================================================
// INTERACTIVE DEMO
// ============================================================================

/**
 * Interactive demo story
 * 
 * This story provides a more interactive experience for testing.
 * It accepts codes starting with "1" to demonstrate the verification flow.
 * 
 * Useful for:
 * - Manual testing of the verification flow
 * - Demonstrating the component to stakeholders
 * - Testing user interactions
 */
export const Interactive: Story = {
  args: {
    ...Default.args,
    onVerify: async (code: string) => {
      // eslint-disable-next-line no-console
      console.log("Verification code submitted:", code);
      
      // Simulate API call delay
      await new Promise((resolve) => setTimeout(resolve, 1500));
      
      // Demo logic: Accept any code starting with "1"
      // This makes it easy to test without a real authenticator app
      if (code.startsWith("1")) {
        return { success: true, message: "2FA setup verified successfully" };
      }
      
      // Reject other codes with helpful message
      return {
        success: false,
        message: "Invalid code. Try a code starting with '1' for demo purposes.",
      };
    },
    onSaveBackupCodes: (codes: string[]) => {
      // eslint-disable-next-line no-console
      console.log("Backup codes to save:", codes);
      // Show alert for demo purposes
      alert(`Backup codes saved:\n${codes.join("\n")}`);
    },
  },
};





