/**
 * Two-Factor Authentication (2FA) Setup Page Component
 * 
 * This component provides a complete 2FA setup flow for users, including:
 * 1. QR code display for authenticator app setup (Google Authenticator, Authy, etc.)
 * 2. Manual code entry option as a backup method
 * 3. Backup codes display and management (one-time use codes)
 * 4. Save/export functionality for backup codes
 * 5. Verification step to confirm the authenticator app is working correctly
 * 
 * @component
 * @example
 * ```tsx
 * <TwoFactorAuthSetupPage
 *   secretKey="JBSWY3DPEHPK3PXP"
 *   accountName="user@example.com"
 *   issuer="Your App"
 *   onVerify={async (code) => {
 *     // Validate code with your backend
 *     return { success: true };
 *   }}
 * />
 * ```
 */

"use client";

import React, { useState, useRef, useEffect } from "react";
import { motion } from "framer-motion";
import { Shield, Copy, Download, CheckCircle2, XCircle, Key } from "lucide-react";
import { cn } from "../../../utils/cn";
import { Button } from "../button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../card";

/**
 * Props interface for the TwoFactorAuthSetupPage component
 */
export interface TwoFactorAuthSetupProps {
  /** 
   * Secret key for authenticator app (usually provided by backend)
   * This is a base32-encoded secret that will be used to generate TOTP codes
   * Example: "JBSWY3DPEHPK3PXP"
   */
  secretKey?: string;
  
  /** 
   * Account identifier (email or username)
   * This will be displayed in the authenticator app
   * Example: "user@example.com"
   */
  accountName?: string;
  
  /** 
   * Issuer name (your app/service name)
   * This helps users identify which service the code is for in their authenticator app
   * Example: "Your App" or "Company Portal"
   */
  issuer?: string;
  
  /** 
   * Backup codes generated by backend
   * These are one-time use codes that can be used if the user loses access to their authenticator app
   * If not provided, default demo codes will be used
   */
  backupCodes?: string[];
  
  /** 
   * Callback function when setup is verified
   * This should validate the 6-digit code with your backend
   * @param code - The 6-digit verification code entered by the user
   * @returns Promise resolving to success status and optional message
   */
  onVerify?: (code: string) => Promise<{ success: boolean; message?: string }>;
  
  /** 
   * Callback function when backup codes are saved
   * This can be used to track that the user has saved their backup codes
   * @param codes - Array of backup codes that were saved
   */
  onSaveBackupCodes?: (codes: string[]) => void;
  
  /** 
   * Visual theme variant
   * - "default": Light theme with subtle gradient
   * - "dark": Dark theme with gray tones
   * - "gradient": Vibrant gradient theme
   */
  variant?: "default" | "dark" | "gradient";
  
  /** 
   * Additional CSS classes to apply to the root container
   */
  className?: string;
}

/**
 * Type definition for the different steps in the 2FA setup flow
 * - "qr": Display QR code for scanning
 * - "manual": Show manual code entry option
 * - "backup": Display backup codes for saving
 * - "verify": Verify the setup with a 6-digit code
 */
type SetupStep = "qr" | "manual" | "backup" | "verify";

/**
 * Main Two-Factor Authentication Setup Page Component
 * 
 * This component manages a multi-step flow:
 * 1. QR Code/Manual Entry → 2. Backup Codes → 3. Verification → Success
 */
const TwoFactorAuthSetupPage: React.FC<TwoFactorAuthSetupProps> = ({
  // Default values for demo/development purposes
  secretKey = "JBSWY3DPEHPK3PXP", // Default demo secret (base32 encoded)
  accountName = "user@example.com",
  issuer = "Your App",
  backupCodes: initialBackupCodes,
  onVerify,
  onSaveBackupCodes,
  variant = "default",
  className,
}) => {
  // ============================================================================
  // STATE MANAGEMENT
  // ============================================================================
  
  /** Current step in the setup flow */
  const [currentStep, setCurrentStep] = useState<SetupStep>("qr");
  
  /** Track if user came from manual entry (affects back button behavior) */
  const [showManualCode, setShowManualCode] = useState(false);
  
  /** Array to store the 6-digit verification code (one digit per input) */
  const [verificationCode, setVerificationCode] = useState<string[]>(Array(6).fill(""));
  
  /** Error message to display if verification fails */
  const [verificationError, setVerificationError] = useState<string | null>(null);
  
  /** Whether verification was successful */
  const [verificationSuccess, setVerificationSuccess] = useState(false);
  
  /** Loading state during verification API call */
  const [isVerifying, setIsVerifying] = useState(false);
  
  /** 
   * Backup codes - one-time use codes for account recovery
   * If not provided via props, use default demo codes
   */
  const [backupCodes] = useState<string[]>(
    initialBackupCodes || [
      "1234-5678",
      "2345-6789",
      "3456-7890",
      "4567-8901",
      "5678-9012",
      "6789-0123",
      "7890-1234",
      "8901-2345",
    ]
  );
  
  /** Track which code was copied (for visual feedback) */
  const [copiedCode, setCopiedCode] = useState<string | null>(null);
  
  /** Reference to the 6 verification input fields for focus management */
  const inputsRef = useRef<Array<HTMLInputElement | null>>([]);

  // ============================================================================
  // QR CODE GENERATION
  // ============================================================================
  
  /**
   * Generate QR code URL using the standard otpauth://totp/ protocol
   * 
   * The QR code contains:
   * - Protocol: otpauth://totp/ (Time-based One-Time Password)
   * - Issuer and account name for identification
   * - Secret key for generating codes
   * 
   * Format: otpauth://totp/{Issuer}:{AccountName}?secret={SecretKey}&issuer={Issuer}
   * 
   * This format is recognized by all major authenticator apps:
   * - Google Authenticator
   * - Authy
   * - Microsoft Authenticator
   * - 1Password
   * - LastPass Authenticator
   */
  const qrCodeUrl = `https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(
    `otpauth://totp/${encodeURIComponent(issuer)}:${encodeURIComponent(accountName)}?secret=${secretKey}&issuer=${encodeURIComponent(issuer)}`
  )}`;

  /**
   * Format the secret key for manual entry
   * Groups the secret into chunks of 4 characters for better readability
   * Example: "JBSWY3DPEHPK3PXP" → "JBSW Y3DP EHPK 3PXP"
   */
  const manualCode = secretKey.match(/.{1,4}/g)?.join(" ") || secretKey;

  // ============================================================================
  // EFFECTS
  // ============================================================================
  
  /**
   * Auto-focus the first verification input when entering the verify step
   * This improves UX by allowing users to immediately start typing
   */
  useEffect(() => {
    if (currentStep === "verify") {
      inputsRef.current[0]?.focus();
    }
  }, [currentStep]);

  // ============================================================================
  // VERIFICATION CODE HANDLERS
  // ============================================================================
  
  /**
   * Handle input change for individual verification code digits
   * 
   * Features:
   * - Only allows numeric input (0-9)
   * - Auto-advances to next input when a digit is entered
   * - Clears error state when user starts typing
   * 
   * @param e - Change event from the input
   * @param index - Index of the input (0-5)
   */
  const handleVerificationChange = (e: React.ChangeEvent<HTMLInputElement>, index: number) => {
    const value = e.target.value;
    
    // Only allow single digit (0-9)
    if (!/^\d?$/.test(value)) return;

    // Update the code array with the new digit
    const newCode = [...verificationCode];
    newCode[index] = value;
    setVerificationCode(newCode);
    
    // Clear any previous errors
    setVerificationError(null);

    // Auto-advance to next input if a digit was entered and not on last input
    if (value && index < 5) {
      inputsRef.current[index + 1]?.focus();
    }
  };

  /**
   * Handle keyboard navigation for verification inputs
   * 
   * Supported keys:
   * - Backspace: Move to previous input if current is empty
   * - Delete: Clear current input
   * - Arrow Left/Right: Navigate between inputs
   * 
   * @param e - Keyboard event
   * @param index - Current input index
   */
  const handleVerificationKeyDown = (
    e: React.KeyboardEvent<HTMLInputElement>,
    index: number
  ) => {
    const key = e.key;
    
    // Backspace: If input is empty, move focus to previous input
    if (key === "Backspace" && !e.currentTarget.value && index > 0) {
      inputsRef.current[index - 1]?.focus();
    }
    
    // Delete: Clear current input
    if (key === "Delete") e.currentTarget.value = "";
    
    // Arrow Left: Move to previous input
    if (key === "ArrowLeft" && index > 0) inputsRef.current[index - 1]?.focus();
    
    // Arrow Right: Move to next input
    if (key === "ArrowRight" && index < 5) inputsRef.current[index + 1]?.focus();
  };

  /**
   * Handle paste event for verification code
   * 
   * Allows users to paste a 6-digit code and it will automatically
   * fill all 6 inputs. Useful when copying from authenticator app.
   * 
   * Features:
   * - Strips whitespace from pasted text
   * - Only accepts numeric input
   * - Limits to 6 digits maximum
   * - Auto-focuses the appropriate input after pasting
   * 
   * @param e - Clipboard event
   * @param index - Index where paste occurred
   */
  const handleVerificationPaste = (e: React.ClipboardEvent<HTMLInputElement>, index: number) => {
    e.preventDefault();
    
    // Get pasted text and remove all whitespace
    const pastedText = e.clipboardData.getData("text").replace(/\s+/g, "");
    
    // Only proceed if pasted text contains only digits
    if (!/^\d+$/.test(pastedText)) return;

    // Extract first 6 digits
    const digits = pastedText.split("").slice(0, 6);
    const newCode = [...verificationCode];
    
    // Fill inputs with pasted digits
    digits.forEach((digit, i) => {
      if (i < 6) newCode[i] = digit;
    });
    setVerificationCode(newCode);

    // Move focus to the next unfilled input (or last input if all filled)
    const nextIndex = Math.min(index + digits.length, 5);
    inputsRef.current[nextIndex]?.focus();
  };

  /**
   * Verify the 6-digit code entered by the user
   * 
   * This function:
   * 1. Validates that all 6 digits are entered
   * 2. Calls the onVerify callback (if provided) to validate with backend
   * 3. Shows success state if verification passes
   * 4. Shows error message if verification fails
   * 
   * In demo mode (no onVerify callback), it accepts any 6-digit code
   */
  const handleVerify = async () => {
    // Join all digits into a single string
    const code = verificationCode.join("");
    
    // Validate that all 6 digits are entered
    if (code.length !== 6) {
      setVerificationError("Please enter the full 6-digit code");
      return;
    }

    // Set loading state
    setIsVerifying(true);
    setVerificationError(null);

    // If onVerify callback is provided, use it to validate with backend
    if (onVerify) {
      try {
        const result = await onVerify(code);
        
        if (result.success) {
          // Verification successful
          setVerificationSuccess(true);
          
          // Notify that backup codes were saved (if callback provided)
          if (onSaveBackupCodes) {
            onSaveBackupCodes(backupCodes);
          }
        } else {
          // Verification failed - show error message
          setVerificationError(result.message || "Invalid code. Please try again.");
        }
      } catch (error) {
        // Handle any errors from the verification API
        setVerificationError("An error occurred. Please try again.");
        console.error("Verification error:", error);
      }
    } else {
      // Demo mode - accept any 6-digit code after a short delay
      setTimeout(() => {
        setVerificationSuccess(true);
        if (onSaveBackupCodes) {
          onSaveBackupCodes(backupCodes);
        }
      }, 1000);
    }

    // Clear loading state
    setIsVerifying(false);
  };

  // ============================================================================
  // BACKUP CODES HANDLERS
  // ============================================================================
  
  /**
   * Copy a single backup code to clipboard
   * 
   * @param code - The backup code to copy
   */
  const handleCopyCode = (code: string) => {
    navigator.clipboard.writeText(code);
    setCopiedCode(code);
    
    // Reset copied indicator after 2 seconds
    setTimeout(() => setCopiedCode(null), 2000);
  };

  /**
   * Copy all backup codes to clipboard (one per line)
   * Useful for users who want to save all codes at once
   */
  const handleCopyAllBackupCodes = () => {
    const codesText = backupCodes.join("\n");
    navigator.clipboard.writeText(codesText);
    setCopiedCode("all");
    
    // Reset copied indicator after 2 seconds
    setTimeout(() => setCopiedCode(null), 2000);
  };

  /**
   * Download backup codes as a text file
   * 
   * Creates a downloadable .txt file containing:
   * - Header text
   * - All backup codes (one per line)
   * - Instructions
   * 
   * The file is automatically downloaded when this function is called
   */
  const handleDownloadBackupCodes = () => {
    // Format the file content
    const codesText = `Two-Factor Authentication Backup Codes\n\n${backupCodes.join("\n")}\n\nSave these codes in a safe place. Each code can only be used once.`;
    
    // Create a Blob with the text content
    const blob = new Blob([codesText], { type: "text/plain" });
    
    // Create a temporary URL for the blob
    const url = URL.createObjectURL(blob);
    
    // Create a temporary anchor element and trigger download
    const a = document.createElement("a");
    a.href = url;
    a.download = "2fa-backup-codes.txt";
    document.body.appendChild(a);
    a.click();
    
    // Clean up
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // ============================================================================
  // STYLING CONFIGURATION
  // ============================================================================
  
  /**
   * Background gradient classes for different variants
   * Applied to the root container
   */
  const variantClasses = {
    default: "bg-gradient-to-br from-background to-muted/20",
    dark: "bg-gradient-to-br from-gray-900 via-gray-800 to-black",
    gradient: "bg-gradient-to-br from-blue-900 via-purple-900 to-pink-900",
  };

  /**
   * Card styling classes for different variants
   * Applied to the main Card component
   */
  const cardVariantClasses = {
    default: "bg-background",
    dark: "bg-gray-800 border-gray-700",
    gradient: "bg-gray-800/90 backdrop-blur-sm border-gray-700",
  };

  // ============================================================================
  // RENDER
  // ============================================================================
  
  return (
    <div
      className={cn(
        "min-h-screen flex items-center justify-center p-4",
        variantClasses[variant],
        className
      )}
    >
      {/* Animated container with fade-in effect */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="w-full max-w-2xl"
      >
        <Card variant="default" className={cn("shadow-2xl", cardVariantClasses[variant])}>
          {/* Header Section */}
          <CardHeader>
            <div className="flex items-center justify-center mb-4">
              {/* Shield icon indicator */}
              <div className="p-3 rounded-full bg-primary/10">
                <Shield className="h-8 w-8 text-primary" />
              </div>
            </div>
            <CardTitle size="lg" className="text-center">
              Set Up Two-Factor Authentication
            </CardTitle>
            <CardDescription className="text-center">
              Secure your account with an extra layer of protection
            </CardDescription>
          </CardHeader>

          <CardContent className="space-y-6">
            {/* ================================================================== */}
            {/* STEP INDICATOR */}
            {/* ================================================================== */}
            {/* 
              Visual progress indicator showing which step the user is on.
              Steps: Setup → Backup Codes → Verify
            */}
            <div className="flex items-center justify-center gap-2 mb-6">
              {[
                { key: "setup", label: "Setup" },
                { key: "backup", label: "Backup Codes" },
                { key: "verify", label: "Verify" },
              ].map((step, index) => {
                // Determine if this step is currently active
                const isActive =
                  (step.key === "setup" && (currentStep === "qr" || currentStep === "manual")) ||
                  (step.key === "backup" && currentStep === "backup") ||
                  (step.key === "verify" && currentStep === "verify");
                
                // Determine if this step has been completed
                const isCompleted =
                  (step.key === "setup" && (currentStep === "backup" || currentStep === "verify")) ||
                  (step.key === "backup" && currentStep === "verify");

                return (
                  <React.Fragment key={step.key}>
                    <div className="flex flex-col items-center">
                      {/* Step number or checkmark */}
                      <div
                        className={cn(
                          "w-8 h-8 rounded-full flex items-center justify-center text-sm font-semibold transition-all",
                          isActive
                            ? "bg-primary text-white"
                            : isCompleted
                            ? "bg-primary/50 text-white"
                            : "bg-muted text-muted-foreground"
                        )}
                      >
                        {isCompleted ? "✓" : index + 1}
                      </div>
                      {/* Step label (hidden on mobile) */}
                      <span className="text-xs mt-1 text-muted-foreground hidden sm:block">
                        {step.label}
                      </span>
                    </div>
                    {/* Connector line between steps */}
                    {index < 2 && (
                      <div
                        className={cn(
                          "h-1 w-12 transition-all mt-4",
                          isCompleted ? "bg-primary" : "bg-muted"
                        )}
                      />
                    )}
                  </React.Fragment>
                );
              })}
            </div>

            {/* ================================================================== */}
            {/* STEP 1: QR CODE DISPLAY */}
            {/* ================================================================== */}
            {currentStep === "qr" && (
              <motion.div
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                className="space-y-6"
              >
                <div className="text-center space-y-2">
                  <h3 className="text-xl font-semibold">Set Up Authenticator App</h3>
                  <p className="text-muted-foreground">
                    Scan this QR code with your authenticator app to add this account.
                  </p>
                  <p className="text-sm text-muted-foreground mt-2">
                    Popular apps: Google Authenticator, Authy, Microsoft Authenticator, 1Password
                  </p>
                </div>

                {/* QR Code Container */}
                <div className="flex justify-center">
                  <div className="p-4 bg-white rounded-lg border-2 border-border">
                    <img
                      src={qrCodeUrl}
                      alt="QR Code for 2FA setup"
                      className="w-48 h-48"
                      onError={(e) => {
                        // Fallback: Hide QR code if it fails to load
                        // In production, you might want to show an error message instead
                        (e.target as HTMLImageElement).style.display = "none";
                      }}
                    />
                  </div>
                </div>

                {/* Action Buttons */}
                <div className="flex gap-3 justify-center">
                  {/* Option to enter code manually instead */}
                  <Button
                    variant="outline"
                    onClick={() => {
                      setCurrentStep("manual");
                      setShowManualCode(true);
                    }}
                  >
                    <Key className="h-4 w-4 mr-2" />
                    Enter Code Manually
                  </Button>
                  {/* Continue to backup codes step */}
                  <Button
                    variant="default"
                    onClick={() => setCurrentStep("backup")}
                  >
                    Continue
                  </Button>
                </div>
              </motion.div>
            )}

            {/* ================================================================== */}
            {/* STEP 1 (ALTERNATIVE): MANUAL CODE ENTRY */}
            {/* ================================================================== */}
            {currentStep === "manual" && (
              <motion.div
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                className="space-y-6"
              >
                <div className="text-center space-y-2">
                  <h3 className="text-xl font-semibold">Enter Code Manually</h3>
                  <p className="text-muted-foreground">
                    If you can't scan the QR code, enter this secret key manually in your authenticator app
                  </p>
                  <p className="text-sm text-muted-foreground mt-2">
                    In your app, select "Enter a setup key" or "Manual entry" and paste this code
                  </p>
                </div>

                {/* Secret Key Display */}
                <div className="bg-muted/50 p-4 rounded-lg border-2 border-dashed border-border">
                  <div className="flex items-center justify-between">
                    {/* Formatted secret key (grouped in 4-character chunks) */}
                    <code className="text-lg font-mono tracking-wider">{manualCode}</code>
                    {/* Copy button */}
                    <Button
                      variant="ghost"
                      size="icon"
                      onClick={() => {
                        // Copy the raw secret key (without spaces) to clipboard
                        navigator.clipboard.writeText(secretKey);
                        setCopiedCode("manual");
                        setTimeout(() => setCopiedCode(null), 2000);
                      }}
                    >
                      {copiedCode === "manual" ? (
                        <CheckCircle2 className="h-4 w-4 text-green-500" />
                      ) : (
                        <Copy className="h-4 w-4" />
                      )}
                    </Button>
                  </div>
                </div>

                {/* Navigation Buttons */}
                <div className="flex gap-3 justify-center">
                  <Button variant="outline" onClick={() => setCurrentStep("qr")}>
                    Back
                  </Button>
                  <Button variant="default" onClick={() => setCurrentStep("backup")}>
                    Continue
                  </Button>
                </div>
              </motion.div>
            )}

            {/* ================================================================== */}
            {/* STEP 2: BACKUP CODES DISPLAY */}
            {/* ================================================================== */}
            {currentStep === "backup" && (
              <motion.div
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                className="space-y-6"
              >
                <div className="text-center space-y-2">
                  <h3 className="text-xl font-semibold">Save Your Backup Codes</h3>
                  <p className="text-muted-foreground">
                    These one-time codes can be used to access your account if you lose access to
                    your authenticator app. Save them in a safe place.
                  </p>
                </div>

                {/* Backup Codes Grid */}
                <div className="bg-muted/50 p-6 rounded-lg border-2 border-dashed border-border">
                  {/* Display all backup codes in a 2-column grid */}
                  <div className="grid grid-cols-2 gap-3 mb-4">
                    {backupCodes.map((code, index) => (
                      <div
                        key={index}
                        className="flex items-center justify-between p-2 bg-background rounded border"
                      >
                        {/* Individual backup code */}
                        <code className="text-sm font-mono">{code}</code>
                        {/* Copy button for individual code */}
                        <Button
                          variant="ghost"
                          size="icon"
                          className="h-6 w-6"
                          onClick={() => handleCopyCode(code)}
                        >
                          {copiedCode === code ? (
                            <CheckCircle2 className="h-3 w-3 text-green-500" />
                          ) : (
                            <Copy className="h-3 w-3" />
                          )}
                        </Button>
                      </div>
                    ))}
                  </div>

                  {/* Bulk Actions */}
                  <div className="flex gap-2 justify-center flex-wrap">
                    {/* Copy all codes at once */}
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={handleCopyAllBackupCodes}
                    >
                      <Copy className="h-4 w-4 mr-2" />
                      {copiedCode === "all" ? "Copied!" : "Copy All"}
                    </Button>
                    {/* Download codes as text file */}
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={handleDownloadBackupCodes}
                    >
                      <Download className="h-4 w-4 mr-2" />
                      Download
                    </Button>
                  </div>
                </div>

                {/* Navigation Buttons */}
                <div className="flex gap-3 justify-center">
                  <Button
                    variant="outline"
                    onClick={() => {
                      // Go back to QR if we came from QR, or to manual if we came from manual
                      setCurrentStep(showManualCode ? "manual" : "qr");
                    }}
                  >
                    Back
                  </Button>
                  {/* Proceed to verification step */}
                  <Button variant="default" onClick={() => setCurrentStep("verify")}>
                    I've Saved My Codes
                  </Button>
                </div>
              </motion.div>
            )}

            {/* ================================================================== */}
            {/* STEP 3: VERIFICATION */}
            {/* ================================================================== */}
            {currentStep === "verify" && !verificationSuccess && (
              <motion.div
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                className="space-y-6"
              >
                <div className="text-center space-y-2">
                  <h3 className="text-xl font-semibold">Verify Setup</h3>
                  <p className="text-muted-foreground">
                    Enter the 6-digit code from your authenticator app to confirm setup
                  </p>
                </div>

                {/* 6-Digit Code Input */}
                <div className="flex gap-2 justify-center">
                  {Array.from({ length: 6 }).map((_, i) => (
                    <input
                      key={i}
                      type="text"
                      inputMode="numeric" // Shows numeric keyboard on mobile
                      maxLength={1} // Only one digit per input
                      ref={(el) => {
                        inputsRef.current[i] = el;
                      }}
                      value={verificationCode[i]}
                      onChange={(e) => handleVerificationChange(e, i)}
                      onKeyDown={(e) => handleVerificationKeyDown(e, i)}
                      onPaste={(e) => handleVerificationPaste(e, i)}
                      className={cn(
                        "w-12 h-14 text-center text-xl font-semibold border-2 rounded-lg",
                        "focus:outline-none focus:ring-2 focus:ring-primary transition-all",
                        // Error state styling
                        verificationError
                          ? "border-red-500 focus:ring-red-500"
                          : "border-border focus:border-primary"
                      )}
                    />
                  ))}
                </div>

                {/* Error Message */}
                {verificationError && (
                  <motion.p
                    initial={{ opacity: 0, y: -10 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="text-sm text-red-500 text-center flex items-center justify-center gap-2"
                  >
                    <XCircle className="h-4 w-4" />
                    {verificationError}
                  </motion.p>
                )}

                {/* Verification Button */}
                <div className="flex gap-3 justify-center">
                  <Button variant="outline" onClick={() => setCurrentStep("backup")}>
                    Back
                  </Button>
                  <Button
                    variant="default"
                    onClick={handleVerify}
                    disabled={isVerifying || verificationCode.join("").length !== 6}
                  >
                    {isVerifying ? "Verifying..." : "Verify & Complete Setup"}
                  </Button>
                </div>
              </motion.div>
            )}

            {/* ================================================================== */}
            {/* SUCCESS STATE */}
            {/* ================================================================== */}
            {verificationSuccess && (
              <motion.div
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                className="text-center py-8 space-y-4"
              >
                {/* Success Icon with Animation */}
                <motion.div
                  initial={{ scale: 0 }}
                  animate={{ scale: 1 }}
                  transition={{ delay: 0.2, type: "spring" }}
                  className="mx-auto w-16 h-16 rounded-full bg-green-500/10 flex items-center justify-center mb-4"
                >
                  <CheckCircle2 className="h-8 w-8 text-green-500" />
                </motion.div>
                
                {/* Success Message */}
                <h3 className="text-xl font-semibold">Two-Factor Authentication Enabled!</h3>
                <p className="text-muted-foreground">
                  Your account is now protected with two-factor authentication. Make sure to keep
                  your backup codes safe.
                </p>
                
                {/* Done Button */}
                <Button variant="default" onClick={() => window.location.reload()}>
                  Done
                </Button>
              </motion.div>
            )}
          </CardContent>
        </Card>
      </motion.div>
    </div>
  );
};

export default TwoFactorAuthSetupPage;
export { TwoFactorAuthSetupPage };




